# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: hal
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod tidy
builds:
- env:
  - CGO_ENABLED=0
  main: ./cmd/hal.go
  ldflags:
    - '-w -X halkyon.io/hal/pkg/hal/cli/version.commit={{.ShortCommit}} -X halkyon.io/hal/pkg/hal/cli/version.version={{.Version}} -X halkyon.io/hal/pkg/hal/cli/version.date={{.Date}}'
  goos:
    - darwin
    - linux
    - windows
  ignore:
    - goos: darwin
      goarch: 386
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
