= Overview of the hal CLI Structure

___________________
Example application
___________________

[source,sh]
----
  # Displays hal help
  hal  --help 
----

hal v0.1.7-3-g6e84308 built with ❤️ by the Halkyon team on 'Thu Sep 19 21:32:33 CEST 2019' (commit: 6e84308) running on top of 'oc'
Easily create and manage Kubernetes applications using Dekorate and the Halkyon operator.

[[syntax]]
Syntax
------


.List of Commands
[width="100%",cols="21%,79%",options="header",]
|===
| Name | Description

| link:#capability[capability]
| Manage capabilities

| link:#component[component]
| Manage components

| link:#link[link]
| Manage links

| link:#version[version]
| Displays this tool's version

|===

[[cli-structure]]
CLI Structure
+++++++++++++

[source,sh]
----
hal : Easily create Kubernetes applications
    capability : Manage capabilities
        create --category --name --parameters --type --version : Create a new capability
        delete : Delete the named capability
    component : Manage components
        create --components : Create a new Halkyon component
        delete : Delete the named component
        mode --components --mode : Switch the component to the provided mode
        push --binary --components : Push a local project to the remote cluster you're connected to
        spring-boot --artifactid --groupid --module --packagename --springbootversion --supported --template --urlservice --version : Create a Spring Boot maven project
    link : Manage links
        create --env --name --secret --target : Link the current (or target) component to the specified capability or component
        delete : Delete the named link
    version : Displays this tool's version

----

[[capability]]
capability
~~~~~~~~~~

[source,sh]
----
capability [flags]
----

_________________
Example using capability
_________________

[source,sh]
----
  # Create a new database capability of type postgres 10 and sets up some parameters as the name of the database and the user/password to connect.
  hal capability create -n db-capability -g database -t postgres -v 10 -p DB_NAME=sample-db -p DB_PASSWORD=admin -p DB_USER=admin

  # Delete the capability named 'foo'
  hal capability delete foo
----

Manage capabilities

[[component]]
component
~~~~~~~~~

[source,sh]
----
component [flags]
----

_________________
Example using component
_________________

[source,sh]
----
  # Create a new Halkyon component found in the 'foo' child directory of the current directory
  hal component create -c foo

  # Delete the component named 'foo'
  hal component delete foo

  # Creates a Spring Boot maven project project using the REST HTTP client template
  hal component spring-boot  \
  -i client-sb \
  -g me.myspringboot \
  -p me.myspringboot.demo \
  -s 2.1.6.RELEASE \
  -t client \
  -v 1.0.0-SNAPSHOT \
  --supported=false  \
  client-sb

  # Deploy the components client-sb, backend-sb
  hal component push -c client-sb,backend-sb

  # Switch the component backend to the provided mode
  hal component mode -c backend-sb -m dev
----

Manage components

[[link]]
link
~~~~

[source,sh]
----
link [flags]
----

_________________
Example using link
_________________

[source,sh]
----
  # links the client-sb to the backend-sb component
 hal link create -n client-to-backend -t client-sb

  # Delete the link named 'foo'
  hal link delete foo
----

Manage links

[[version]]
version
~~~~~~~

[source,sh]
----
version
----

_________________
Example using version
_________________

[source,sh]
----
hal version
----





