= Overview of the hal CLI Structure

___________________
Example application
___________________

[source,sh]
----
  # Displays hal help
  hal  --help 
----

hal v0.1.5-10-g8ec1839 built with ❤️ by the Snowdrop team on 'Fri Sep 13 12:41:17 CEST 2019' (commit: 8ec1839) running on top of 'oc'
Easily create and manage Kubernetes applications using Dekorate and the Halkyon operator.

[[syntax]]
Syntax
------


.List of Commands
[width="100%",cols="21%,79%",options="header",]
|===
| Name | Description

| link:#capability[capability]
| Create a new capability

| link:#component[component]
| Manage components

| link:#link[link]
| Link the current (or target) component to the specified capability or component

| link:#version[version]
| Displays this tool's version

|===

[[cli-structure]]
CLI Structure
+++++++++++++

[source,sh]
----
hal : Easily create Kubernetes applications
    capability --category --name --parameters --type --version : Create a new capability
    component : Manage components
        mode --components --mode : Switch the component to the provided mode
        push --components : Push a local project to the remote cluster you're connected to
        spring-boot --artifactid --groupid --module --packagename --springbootversion --supported --template --urlservice --version : Create a Spring Boot maven project
    link --env --name --secret --target : Link the current (or target) component to the specified capability or component
    version : Displays this tool's version

----

[[capability]]
capability
~~~~~~~~~~

[source,sh]
----
capability [flags]
----

_________________
Example using capability
_________________

[source,sh]
----
  # Create a new database capability de type postgres 10 and sets up some parameters as the name of the database and the user/password to connect.
  hal capability -n db-capability -g database -t postgres -v 10 -p DB_NAME=sample-db -p DB_PASSWORD=admin -p DB_USER=admin
----

Create a new capability

[[component]]
component
~~~~~~~~~

[source,sh]
----
component [flags]
----

_________________
Example using component
_________________

[source,sh]
----
  # Creates a Spring Boot maven project project using the REST HTTP client template
  hal component spring-boot  \
  -i client-sb \
  -g me.myspringboot \
  -p me.myspringboot.demo \
  -s 2.1.6.RELEASE \
  -t client \
  -v 1.0.0-SNAPSHOT \
  --supported=false  \
  client-sb

  # Deploy the components client-sb, backend-sb
  hal component push -c client-sb,backend-sb

  # Switch the component backend to the provided mode
  hal component mode -c backend-sb -m dev
----

Manage components

[[link]]
link
~~~~

[source,sh]
----
link [flags]
----

_________________
Example using link
_________________

[source,sh]
----
  # links the client-sb to the backend-sb component
 hal link -n client-to-backend -t client-sb
----

Link the current (or target) component to the specified capability or component

[[version]]
version
~~~~~~~

[source,sh]
----
version
----

_________________
Example using version
_________________

[source,sh]
----
hal version
----





