version: 2
jobs:
  release:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash
  snapshot:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: Build container image of hal and publish it on quay under halkyonio org
          command: |
            VERSION=master
            make build
            docker build -t hal:${VERSION} -f build/Dockerfile .
            TAG_ID=$(docker images -q hal:${VERSION})
            docker tag ${TAG_ID} quay.io/halkyonio/hal:${VERSION}
            docker login quay.io -u="${QUAY_ROBOT_USER}" -p="${QUAY_ROBOT_TOKEN}"
            docker push quay.io/halkyonio/hal:${VERSION}

      - run: curl -sL https://git.io/goreleaser | bash -s -- --snapshot
      - run: ./dist/hal_linux_386/hal
      - store_artifacts:
          path: ./dist
workflows:
  version: 2
  release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
      - snapshot:
          filters:
            branches:
              only: master